### PR TITLE
V0.1.0 of Lava-optimization

### PR DESCRIPTION
**Pull request by ashishrao7**
This pull request is v0.1.0 of the lava-optimization library. It references issues #2 and #3 . It contains the first version of the QP solver and a tutorial for using QP solvers to implement LASSO.
Reviewers: @GaboFGuerra @awintel and Sumedh

### CODE REVIEW

**Review by phstratmann — CHANGES_REQUESTED** [review]
Have not reviewed everything, only up to models.py.

In general, awesome work :-)

Link to Lava installation tutorial not working.

Qp_example.py:
-	Docstring, "equality constraints" with minor letter, new line for equality cnstraints
-	Would be great if you could print the results (or is this part of the solver.solve?)


Constraints.py
-	The descriptions of the params (var_subset, relation) are hard to be understood. What exactly do they look like? What data type? A user should look at this docstring and know exactly what he/she needs to input without looking into the further code.
-	ContinousConstraint
o	no definition of the inputs. 
o	Constraint_terms = kwargs looks like bad code for me; I would expect something like kwargs.get(…). Otherwise, there is a high chance that a user just specified wrong kwargs

Cost.py
-	Docstring: 
o	"or _those".
o	What do you mean by "those incorporating constraints into the costs"? By regularization?
o	What does the tuple of terms look like? What are the elements?
-	Cost_terms = kwargs. Like above, I dislike this definition. I would rather explicitly kwargs.get for each three inputs. But I may be wrong.
-	"whether the cost function only includeS"
-	Def is_linear: Maybe more elegant to avoid using if-clause and use something like "return not self.is_linear is None" (check if this works). Similar for functions below.
-	You have no function defined to get augmented terms?

Problems.py
-	Abstract CONSTRAINT optimization problem
-	Define input params in docstring
-	QP docstring
o	I think you need an empty line before defining the params
o	Definition of Inequality terms in docstring in new line
o	No empty line after the last param
o	In the params, I would like to see what data type you would expect. E.g. how do I insert a hyperplane?
-	QP: 
o	I think p may be left undefined. In that case, you would simply initialize p with zeros.
o	For definition of A etc: The test "if A is not None" is a bit useless if you define A as none otherwise?
o	Minor letter for variables like Q, A, A_eq
Processes.py:
-	"Listener for solver network solution message reads solution when found."??

Solver.py
-	OptimizatioSolver docstring
o	kwargs with minor letter. But this definition of kwargs is great – could you use it also in the other classes?
-	Def problem: :return in docstring without explanation?
-	Def __init__: why are you giving **kwargs if none are used?
-	Def problem: no docstring
-	Maybe use "def get_problem" and "def set_problem" instead of using "def problem(…)" for both? But please correct me. Same for solver_net, integrator
-	Def _build: I found the ":param" in the docstring only define input to the method, or am I wrong?
-	- def solve: 
o	With the current definition, you will have to give a "problem" even when "problems" is defined. Is that on purpose?
o	Params in docstring should have same order as in method def
o	Maybe worth to give a default value for timeout?
o	L 119: does the if-clause work if _check_solution returns pass? Not sure.

Models.py
-	L119, l125: "fixed point"
-	L168, l 217: define params in docstring
-	L221: minor letters for variables

**Review by mathisrichter — CHANGES_REQUESTED** [review]
### General

- Add type hints throughout using typing module
- Convert all docstrings to numpy format


### problems/problems.py
- arguments Q, A, A_eq should be lowercase
- I would find the code much more readable if these variables had
  descriptive names...for instance:
  Q: quadratic_term
  p: linear_term
  A: ineq_hyperplanes
  k: ineq_offsets
  A_eq: eq_hyperplanes
  k_eq: eq_offsets
- lines 42-51: Do you need the if-elses? Can't you just do self._A = A etc.?
- Use a more specific exception type
- Exception messages could be more descriptive
- typos in the docstring

### problems/constraints.py
- It seems like AbstractConstraint may need to be redesigned. There seem
to be different types of constraints
(discrete, linear, mixed, etc.) and you seem to encode that by having
a (boolean?) flag "is_discrete" in the abstract class. Why is this
necessary if you have a subclass DiscreteConstraint?
If you want to use inheritance, the abstract class should only provide
the interface that is shared by all subclasses while they implement
the behavior and add whatever is specific to them.
Alternatively, this may be designed using composition rather than
inheritance.
This may be a larger task. If you don't want to do this now, please create
an issue for this and do it later.

- Continuous constraint is missing validation of input arguments

### problems/cost.py
- There seems to be some overlap in the methods between Cost and
AbstractConstraint. This may be taken into consideration when designing
the classes.
- Instead of using a _cost_terms dictionary, having dedicated variables
in the class for the individual cost terms would be more explicit and
easier to read. Same for AbstractConstraints var_subset.
- Why is Cost._cost_terms 'protected' and AbstractConstraints.var_subset
'public'?

### solvers/qp/processes.py
- GradientDynamics: variables (e.g., A_T) should be lowercase

### solvers/qp/solver.py
- line 34: self._problem should be defined in __init__()
- line 19: kwargs argument unused in __init__()
- solve(): multiple args unused
- multiple linter errors on this file (in PyCharm, haven't checked with pyb)

### solvers/qp/models.py
- missing at least minimal docstrings for classes and some comments
throughout

### Unit tests

- Generally: Do not use randomly generated numbers in unit tests.
Unit tests have to be deterministic otherwise a test that was passing
on your system before you pushed may fail in production.
Test all qualitatively different combinations of inputs. Use for loops
with subtests (with self.subTest(msg="description"):) if required,
to avoid code duplication.

- Unit tests for cost.py do not exist

- Unit tests for problems.py do not exist

- I would remove all empty classes, function headers, and unit tests.

- Remove failing placeholder unit test in test_solver.py

**Comment by ashishrao7** [comment]
Hi Phlipp, thank you for the review. Addressed your issues in commit 9b608bfc4bc2c19d3d0e6dfb9bd86be6231cc613. Still have to work on Mathis' review which will take time. Advise you to look at the repo after that.
> Qp_example.py:
> 
> * Docstring, "equality constraints" with minor letter, new line for equality cnstraints

Resolved
> * Would be great if you could print the results (or is this part of the solver.solve?)
>
Part of solver.solve

> Constraints.py
> 
> * The descriptions of the params (var_subset, relation) are hard to be understood. What exactly do they look like? What data type? A user should look at this docstring and know exactly what he/she needs to input without looking into the further code.
> * ContinousConstraint
>   o	no definition of the inputs.
>   o	Constraint_terms = kwargs looks like bad code for me; I would expect something like kwargs.get(…). Otherwise, there is a high chance that a user just specified wrong kwargs
> 
> Cost.py
> 
> * Docstring:
>   o	"or _those".
>   o	What do you mean by "those incorporating constraints into the costs"? By regularization?
>   o	What does the tuple of terms look like? What are the elements?
> * Cost_terms = kwargs. Like above, I dislike this definition. I would rather explicitly kwargs.get for each three inputs. But I may be wrong.
> * "whether the cost function only includeS"
> * Def is_linear: Maybe more elegant to avoid using if-clause and use something like "return not self.is_linear is None" (check if this works). Similar for functions below.
> * You have no function defined to get augmented terms?
> 
WIP files, removed from PR. Above issues resolved for now. Feedback will be kept in mind for next release

> Problems.py
> 
> * Abstract CONSTRAINT optimization problem

resolved
> * Define input params in docstring
> * QP docstring
>   o	I think you need an empty line before defining the params
>   o	Definition of Inequality terms in docstring in new line
>   o	No empty line after the last param
>   o	In the params, I would like to see what data type you would expect. E.g. how do I insert a hyperplane?
All the above docstring issues have been resolved.

> * QP:
>   o	I think p may be left undefined. In that case, you would simply initialize p with zeros.

Good point. Added that support

>   o	For definition of A etc: The test "if A is not None" is a bit useless if you define A as none otherwise?

The tests was to ensure that the k corresponding to A is not undefined if A is defined and vice-versa

>   o	Minor letter for variables like Q, A, A_eq

Used Major letter for variables here since that's how other solvers provide their interface. Minor letters can be confused
for vectors instead of matrices

>   Processes.py:
> * "Listener for solver network solution message reads solution when found."??
 
I did not understand the above issue
 
> Solver.py
> 
> * OptimizatioSolver docstring
>   o	kwargs with minor letter. But this definition of kwargs is great – could you use it also in the other classes?
> * Def problem: :return in docstring without explanation?
> * Def **init**: why are you giving **kwargs if none are used?
> * Def problem: no docstring

> * Maybe use "def get_problem" and "def set_problem" instead of using "def problem(…)" for both? But please correct me. Same for solver_net, integrator

> * Def _build: I found the ":param" in the docstring only define input to the method, or am I wrong?
> * * def solve:
>     o	With the current definition, you will have to give a "problem" even when "problems" is defined. Is that on purpose?
>     o	Params in docstring should have same order as in method def
>     o	Maybe worth to give a default value for timeout?
>     o	L 119: does the if-clause work if _check_solution returns pass? Not sure.
> 
The files have been removed from the PR for this release. Your inputs will be incorporated in the next release
> Models.py
> 
> * L119, l125: "fixed point"

Resolved
> * L168, l 217: define params in docstring

the behavior is defined in the corresponding models docstring. Lava core also had no docstrings for processes models. After an internal discussion. It was decided that processModels don't have to have docstrings if they are well-documented in the process.py unless they do something very non-obvious.

> * L221: minor letters for variables

All variables except "A_T" are in minor letters. "A_T " is left in major letters for convenience of the reader for reasons mentioned before about standards solvers

**Comment by awintel** [comment]
> ... It was decided that processModels don't have to have docstrings if they are well-documented in the process.py unless they do something very non-obvious.

What I meant to say was that ProcModels do not necessarily require a docstring since the API of the Proc is defined in the Process class and otherwise the ProcModel only implements the behavioral model of the Proc according to standard conventions.
However, if there's anything interesting to say about the way the ProcModel implements the Proc then this could be mentioned in the ProcModel class. I.e.:
- What's the purpose of this particular ProcModel (bit-accurate vs. non-bit-accurate, in what way is it not accurate)?
- Is there anything else specific about the way it's implemented?
- Is there anything specific to say about when users should use it?
- Caveats about using it?

We don't have to write docstring for the sake of documenting. But if it provides value, we should mention it.

Also all functional code should usually have comments that demonstrate the intent if necessary.

**Comment by awintel** [comment]
Did this get mentioned already:
> from src.lava.lib.optimization.solvers.qp.processes import (
    ConstraintCheck,
    ConstraintNeurons,
    SolutionNeurons,
    ConstraintNormals,
    ConstraintDirections,
    QuadraticConnectivity,
    GradientDynamics,
)
Something seems wrong with the import path: There shouldn't be src. It needs to start from lava...

**Comment by awintel** [comment]
@ashishrao7 There's also a file called qp_example.py in the root directory of the repo.

**Comment by GaboFGuerra** [comment]
> @ashishrao7 Did this get mentioned already:
> 
> > from src.lava.lib.optimization.solvers.qp.processes import (
> > ConstraintCheck,
> > ConstraintNeurons,
> > SolutionNeurons,
> > ConstraintNormals,
> > ConstraintDirections,
> > QuadraticConnectivity,
> > GradientDynamics,
> > )
> > Something seems wrong with the import path: There shouldn't be src. It needs to start from lava...

@awintel, the src folder was added by @mgkwill with his CI/CD configuration.

**Comment by ashishrao7** [comment]
Hi Mathis. Thank you for your feedback. Most of the issues have been addressed  (excluding typing which will be done soon)
in commit a37b77af92f59f296079e8226930dbc928d21b39. Please find the replies below
> ### General
> * Add type hints throughout using typing module
Will be resolved soon
> * Convert all docstrings to numpy format

Resolved 

> ### problems/problems.py
> * arguments `Q`, `A`, `A_eq` should be lowercase
> * I would find the code much more readable if these variables had
>   descriptive names...for instance:
>   Q: quadratic_term
>   p: linear_term
>   A: ineq_hyperplanes
>   k: ineq_offsets
>   A_eq: eq_hyperplanes
>   k_eq: eq_offsets

arguments are in uppercase since that's how other solvers also do it and that's more intuitive to users who have used other 
QP solvers.
 
> * lines 42-51: Do you need the if-elses? Can't you just do `self._A = A` etc.?

This was done to ensure that the user supplies both A and k matrices and not either one of them. The design here is temporary and will be modified for a future release when the abstract solvers and problem classes are coded out. Atm it's a scaffold to mainly make models.py and process.py in solvers/qp to work

> * Use a more specific exception type

Resolved

> * Exception messages could be more descriptive

Made it a little longer. Resolved

> * typos in the docstring

Resolved

> ### problems/constraints.py
> * It seems like `AbstractConstraint` may need to be redesigned. There seem to be different types of constraints (discrete, linear, mixed, etc.) and you seem to encode that by having a (boolean?) flag `is_discrete` in the abstract class. Why is this necessary if you have a subclass `DiscreteConstraint`?
>   If you want to use inheritance, the abstract class should only provide the interface that is shared by all subclasses while they implement the behavior and add whatever is specific to them.
>   Alternatively, this may be designed using composition rather than inheritance.
>   This may be a larger task. If you don't want to do this now, please create an issue for this and do it later.
> * Continuous constraint is missing validation of input arguments
> 
> ### problems/cost.py
> * There seems to be some overlap in the methods between `Cost` and `AbstractConstraint`. This may be taken into consideration when designing the classes.
> * Instead of using a `_cost_terms` dictionary, having dedicated variables in the class for the individual cost terms would be more explicit and easier to read. Same for `AbstractConstraints.var_subset`.
> * Why is Cost._cost_terms protected and `AbstractConstraints.var_subset`
>   public?

The above two files have been removed from this PR hence resolved. Your inputs will be incorporated in the next release. 
 
> ### solvers/qp/processes.py
> * `GradientDynamics`: variables (e.g., `A_T`) should be lowercase

All variables except "A_T" are in minor letters. "A_T " is left in major letters for convenience of the reader for reasons mentioned before about standards solvers

> ### solvers/qp/solver.py
> * line 34: `self._problem` should be defined in `__init__()`

self._problem was decided to not be an attribute of the solver class. It's an argument that gets passed to the solve() function

> * line 19: `kwargs` argument unused in `__init__()`
> * `solve()`: multiple args unused

Above comments resolved

> * multiple linter errors on this file (in PyCharm, haven't checked with pyb)

I ran flake8 checks and used black as my linter. It appears to pass CI/CD which has flake8 requirements

> ### solvers/qp/models.py
> * missing at least minimal docstrings for classes and some comments
>   throughout

> ### Unit tests
> * Generally: Do not use randomly generated numbers in unit tests. Unit tests have to be deterministic otherwise a test that was passing on your system before you pushed may fail in production. Test all qualitatively different combinations of inputs. Use for loops with subtests (`with self.subTest(msg="description"):`) if required, to avoid code duplication.

No random numbers in unittests for models and processes now. 

> * Unit tests for cost.py do not exist

File removed from this PR therefore resolved.

> * Unit tests for problems.py do not exist

File removed from this PR therefore resolved.

> * I would remove all empty classes, function headers, and unit tests.

Resolved

> * Remove failing placeholder unit test in test_solver.py

resolved

**Comment by ashishrao7** [comment]
> > @ashishrao7 Did this get mentioned already:
> > > from src.lava.lib.optimization.solvers.qp.processes import (
> > > ConstraintCheck,
> > > ConstraintNeurons,
> > > SolutionNeurons,
> > > ConstraintNormals,
> > > ConstraintDirections,
> > > QuadraticConnectivity,
> > > GradientDynamics,
> > > )
> > > Something seems wrong with the import path: There shouldn't be src. It needs to start from lava...
> 
> @awintel, the src folder was added by @mgkwill with his CI/CD configuration.

Addressed in commit a37b77af92f59f296079e8226930dbc928d21b39

**Comment by mathisrichter** [comment]
Looks good now, thanks for addressing all of those issues, Ashish.

I just noticed this:
- solver.py, lines 54-59: You are accessing protected members of the `QP` class, for instance `problem._Q`. If you need read-access to these variables, add a `@property` method `Q` to the `QP` class and use `problem.Q` instead. Actually, for `_Q` you already have the `hessian()` property. But you'll need to add more property methods for other members.

**Review by mathisrichter — CHANGES_REQUESTED** [review]
Looks good now, thanks for addressing all of those issues, Ashish.

I just noticed these:
- solver.py, lines 54-59: You are accessing protected members of the `QP` class, for instance `problem._Q`. If you need read-access to these variables, add a `@property` method `Q` to the `QP` class and use `problem.Q` instead. Actually, for `_Q` you already have the `hessian()` property. But you'll need to add more property methods for other members.
- Remove the \_\_init\_\_.py file from the top-level directory.
- solver.py still has `src` imports
- solvers/qp/utils.py is empty and should be removed
- no need for prints at the end of unit tests that state that the test passed; remove those

**Comment by ashishrao7** [comment]
> Looks much better now, thanks for addressing all of those issues, Ashish.
> 
> A few more things to change:
> 
> * solver.py, lines 54-59: You are accessing protected members of the `QP` class, for instance `problem._Q`. If you need read-access to these variables, add a `@property` method `Q` to the `QP` class and use `problem.Q` instead. Actually, for `_Q` you already have the `hessian()` property. But you'll need to add more property methods for other members.
> * Remove the __init__.py file from the top-level directory.
> * solver.py still has `src` imports
> * solvers/qp/utils.py is empty and should be removed
> * no need for prints at the end of unit tests that state that the test passed; remove those

Thanks for the review. Fixed all the above issue in commit 93d0bd7834954e062838f032812322fd872148cd. Need to add typing which I'll look into after I fix a small bug that's more critical atm

**Review by mathisrichter — APPROVED** [review]

**Review by mathisrichter — CHANGES_REQUESTED** [review]
Great! I already approved but now there is one last thing...

You argued before that the users of the library would be intimately familiar with the member names `Q`, `p`, etc. and that it would not be helpful to rename them to more descriptive names. The `@property` methods for those members have descriptive names now (`get_hessian()` returns `self._Q`). I suggest sticking either with the math-inspired or the descriptive names throughout to be consistent.

Apart from that everything looks good.

**Comment by ashishrao7** [comment]
> Great! I already approved but now there is one last thing...
> 
> You argued before that the users of the library would be intimately familiar with the member names `Q`, `p`, etc. and that it would not be helpful to rename them to more descriptive names. The `@property` methods for those members have descriptive names now (`get_hessian()` returns `self._Q`). I suggest sticking either with the math-inspired or the descriptive names throughout to be consistent.

I changed this to be more consistent like you suggested. Matched it to the interface.

> Apart from that everything looks good.

Also added typing now

**Review by mgkwill — APPROVED** [review]
Looks good to me (LGTM).

setup.py is auto generated, but formatting it is fine.

For consistency sake:
src/lava/lib/optimization/__init__.py does not have copyright header.
src/lava/lib/optimization/solvers/__init__.py does not have copyright header.

I don't think we should have src/__init__.py, but we can test without and fix later

**Comment by ashishrao7** [comment]
> Looks good to me (LGTM).
> 
> setup.py is auto generated, but formatting it is fine.
> 
> For consistency sake: src/lava/lib/optimization/**init**.py does not have copyright header. src/lava/lib/optimization/solvers/**init**.py does not have copyright header.
> 
> I don't think we should have src/**init**.py, but we can test without and fix later
> 
> After our conversation we should follow lowercase var names in src/lava/lib

Resolved all comment in commit b09944e1b2a14ddb1e5d825290c9ff5ef40f703d

**Review by phstratmann — APPROVED** [review]
My comments were all handled well and resolved, thanks Ashish!

Please note: Due to time restrictions, I only covered ~50% of the code and not to full depth.

**Review by mathisrichter — APPROVED** [review]

**Review by GaboFGuerra — APPROVED** [review]
Looks good!

**Review by mgkwill — APPROVED** [review]

**Comment by mgkwill** [comment]
Only failure in CI is because of long path on windows. False positive. Merging.

**Pull request merged**
