### PR TITLE
Lava-optimization v0.1.1 Changes

### PR DESCRIPTION
**Pull request by ashishrao7**
Deleted examples/ , moved tutorials/ inside src/ , changed image in qp tutorial and made some formatting changes in the README

### CODE REVIEW

**Review by mgkwill — CHANGES_REQUESTED** [review]
https://github.com/lava-nc/lava-optimization/blob/7e808d37eff9442cff3240e736b1013a396a2e38/README.md?plain=1#L31

I think you need to add src dir and change above link to 
```
https://github.com/lava-nc/lava-optimization/tree/main/src/tutorials/qp/tutorial_01_solving_lasso.ipynb
```

Are there any other places where links need to be changed?

**Comment by mgkwill** [comment]
https://github.com/lava-nc/lava-optimization/blob/7e808d37eff9442cff3240e736b1013a396a2e38/README.md?plain=1#L31

> https://github.com/lava-nc/lava-optimization/blob/7e808d37eff9442cff3240e736b1013a396a2e38/README.md?plain=1#L31
> 
> I think you need to add src dir and change above link to
> 
> ```
> https://github.com/lava-nc/lava-optimization/tree/main/src/tutorials/qp/tutorial_01_solving_lasso.ipynb
> ```
> 
> Are there any other places where links need to be changed?

Also lava-nc/lava has a dir structure of src/lava/tutorials, if this change is for consistency we need to match lava-nc/lava

**Comment by ashishrao7** [comment]
> https://github.com/lava-nc/lava-optimization/blob/7e808d37eff9442cff3240e736b1013a396a2e38/README.md?plain=1#L31
> 
> > https://github.com/lava-nc/lava-optimization/blob/7e808d37eff9442cff3240e736b1013a396a2e38/README.md?plain=1#L31
> > I think you need to add src dir and change above link to
> > ```
> > https://github.com/lava-nc/lava-optimization/tree/main/src/tutorials/qp/tutorial_01_solving_lasso.ipynb
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Are there any other places where links need to be changed?
> 
> Also lava-nc/lava has a dir structure of src/lava/tutorials, if this change is for consistency we need to match lava-nc/lava https://github.com/lava-nc/lava/tree/main/src/lava/tutorials
> 
> It might make sense to then have a dir at src/lava/tutorials that contains your specific tutorial to match already present tutorials.

I'm aware that the tutorials in lava are under src/lava/ but @awintel had communicated to me to put tutorials under src/. Is putting it under src/lava/ what we are sticking to for all repos?

**Review by awintel — APPROVED** [review]
Rename LAVA to Lava.

For the rest, see email that I sent...

**Review by mgkwill — COMMENTED** [review]
Did we come a decision on location of tutorials across all libs?

**Review by mgkwill — APPROVED** [review]

**Comment by awintel** [comment]
Create a poll...

**Pull request merged**
